services:
  app:
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-olinda_user}:${SERVICE_PASSWORD_64_POSTGRES}@olinda-db:5432/${POSTGRES_DB:-olinda_db}
    networks:
      - default
      - coolify
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.olinda-https.redirectscheme.scheme=https
      - traefik.http.routers.olinda-http.entrypoints=http
      - traefik.http.routers.olinda-http.rule=Host(`olinda.portaprojetos.online`)
      - traefik.http.routers.olinda-http.middlewares=olinda-https
      - traefik.http.routers.olinda.entrypoints=https
      - traefik.http.routers.olinda.rule=Host(`olinda.portaprojetos.online`)
      - traefik.http.routers.olinda.tls=true
      - traefik.http.routers.olinda.tls.certresolver=letsencrypt
      - traefik.http.services.olinda.loadbalancer.server.port=5000

  postgres:
    networks:
      default:
        aliases:
          - olinda-db

networks:
  coolify:
    external: true
    name: coolify
